# Use postgres/example user/password credentials
# Default DB name is "postgres", default schema is "public"
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - data_postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  data_postgres: